#!/bin/bash

END_DATE="2017-05-12 14:00:00"
URGENT_VALUE=86400
END_DATE=$(date --date="${END_DATE}" '+%s')
CUR_DATE=$(date "+%s")
DIFF_DATE=$((END_DATE - CUR_DATE))
DIFF=""

if [[ "${DIFF_DATE}" -le 0 ]]
then
	DIFF=$(date -u -d "@$(( DIFF_DATE * -1))" +"%H:%M:%S")
	echo "${DIFF}"
	echo "${DIFF}"
	echo ""
	exit 33
fi

if [[ "${DIFF_DATE}" -ge 86400 ]]
then
	DIFF="[$((DIFF_DATE / 86400))] "
fi

DIFF+=$(date -u -d "@${DIFF_DATE}" +"%H:%M:%S")

echo "${DIFF}"
