#!/bin/bash

CARD="1"

case "${BLOCK_BUTTON}"
in
	1) amixer -c${CARD} -q sset Capture 5%+		;;
	2) amixer -c${CARD} -q sset Capture toggle	;;
	3) amixer -c${CARD} -q sset Capture 5%-		;;
esac

statusLine=$(amixer -c${CARD} get Capture | tail -n 1)
status=$(echo "${statusLine}" | grep -wo "on")
volume=$(echo "${statusLine}" | awk -F ' ' '{print $5}' | tr -d '[]%')

if [[ "${status}" == "on" ]]
then
	echo "${volume}%"
	echo "${volume}%"
	echo ""
else
	echo "off"
	echo "off"
	echo ""
fi
