#!/bin/sh
xrandr					\
	--output HDMI1 --off		\
	--output HDMI2 --off		\
	--output VIRTUAL1 --off		\
	--output DP1			\
		--mode 1024x768		\
		--pos 0x0		\
		--rotate normal		\
	--output eDP1			\
		--mode 1366x768		\
		--pos 1024x0		\
		--rotate normal
xrandr --output eDP1 --primary
