#!/bin/bash

xrandr					\
	--output HDMI-1 --off		\
	--output eDP-1  --off		\
	--output HDMI-2	--off		\
	--output DP-1			\
		--primary		\
		--mode 1920x1080	\
		--pos 0x0		\
		--rotate normal

xrandr --output DP-1 --primary

cmd=$(grep '/usr/bin/feh' ~/.i3/config | sed 's/exec --no-startup-id //')
eval ${cmd}
i3-msg restart
