#!/bin/bash
xrandr					\
	--output HDMI-1 --off		\
	--output HDMI-2 --off		\
	--output eDP-1  --off		\
	--output DP-1			\
		--mode 1280x1024	\
		--pos 0x0		\
		--rotate normal		\
		--primary
xrandr --output DP-1 --primary

cmd=$(grep '/usr/bin/feh' ~/.i3/config | sed 's/exec --no-startup-id //')
eval ${cmd}
i3-msg restart
