#!/bin/bash

# Toggle sound
# This script is called from ~/.config/.i3/config

amixer -D pulse set Master Playback Switch toggle >/dev/null 2>&1
state=$(amixer get Master	| \
	awk '/Left:/ { gsub(/[\[\]]/, ""); print $6}')
notify-send "Sound: ${state}"
