# vi: set sw=4 ts=4 ai:

source ~/.zsh/z_host_specific

# set my umask
umask 022

# on
setopt sh_nullcmd
setopt autocd
setopt autopushd
setopt pushdignoredups
setopt promptsubst
setopt correct
setopt rm_starsilent
setopt hist_ignore_dups
setopt magicequalsubst
setopt share_history
setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_space
setopt no_nomatch
setopt extended_glob
setopt braceccl
setopt complete_in_word
setopt hash_listall
setopt nohup
setopt notify

# off
unsetopt globalrcs
unsetopt bgnice

# completion
autoload -Uz compinit
compinit

# multiple move
autoload zmv

# help subsystem (you gotta know this one)
autoload run-help

# source helper files
source ~/.zsh/zexit
source ~/.zsh/zsshmaster
source ~/.zsh/zalias
source ~/.zsh/zfunction
source ~/.zsh/zkeys
source ~/.zsh/zstyles
source ~/.zsh/zexport
source ~/.zsh/zgpg
# source ~/.zsh/zprompt

# Emacs commandline editing
# I hate the editor, but I love the commandline
bindkey -e

if [[ ${TERM:-} = "linux" ]]
then
	# turn annoying beep off
	setterm -blength 0
fi

#cd
