#------------------------------------------------------------------------------#
# vi: set sw=4 ts=4 ai:                            ("set modeline" in ~/.exrc) #
#------------------------------------------------------------------------------#

#------------------------------------------------------------------------------#
# $Id:: zshenv 10 2009-08-09 15:21:03Z tonk                                 $: #
# $Revision:: 10                                                            $: #
# $Author:: Ton Kersten <TonK@Wanadoo.nl>                                   $: #
# $Date:: 2009-08-09 17:23:10 +0200 (Sun, 09 Aug 2009)                      $: #
# $Hash:: 02096d275fe3ed27440585bf575f39e072d8d88f (tonk)                   $: #
#------------------------------------------------------------------------------#

# No files from the system
unsetopt globalrcs

source ~/.zsh/z_host_specific
source ~/.zsh/zkeys
source ~/.zsh/zalias
source ~/.zsh/zfunction
source ~/.zsh/zexport
source ~/.zsh/zprofile
source ~/.zsh/zprompt

[[	(${TERM_PROFILE} != "cursus" )	&&	\
	( ${-} = *i*                 )	&&	\
	( -x ~/roken                 ) ]] && ~/roken
