# vi: set sw=4 ts=4 ai:

# No files from the system
unsetopt globalrcs

source ~/.zsh/z_host_specific
source ~/.zsh/zkeys
source ~/.zsh/zalias
source ~/.zsh/zfunction
source ~/.zsh/zexport
source ~/.zsh/zprofile
# source ~/.zsh/zprompt

[[	(${TERM_PROFILE} != "cursus" )	&&	\
	( ${-} = *i*                 )	&&	\
	( -e ~/README                ) ]] && cat ~/README
